<style type="text/css">

    .tengah {
        position: absolute;
        margin-left: auto;
        margin-right: auto;
        margin-top: auto;
        margin-bottom: auto;
        left: 35%;
        right: 35%;
        top: 20%;
        bottom: 25%;
    }

</style>
<div class="tengah">
        <div class="col-md-12 card" >

            <img src="img/error.png" width="150" height="150" >

            <div  class="col-lg-12" >

                <p><?php echo $this->flashSession->output() ?></p>

                <?= $this->tag->form('login/login'); ?>
                <div class="form-group">
                    <label class="small float-left"><b>E-mail :</b></label>
                    <?= $form->render('email'); ?>
                </div>
                <div class="form-group">
                    <label class="small float-left"><b>Password :</b></label>
                    <?= $form->render('password'); ?>
                </div>

                <div class="row lg-12 ">
                    <div class=" col-lg-7" align="left">
                        <div class="form-group">
                            <?= $form->render('cek'); ?>
                            <label id="showpass">Show Password</label>
                        </div>
                    </div>
                    <div class="col-lg-5" align="right">
                        <?= $form->render('submit');  ?>
                    </div>
                </div>
                <div class="form-group" align="center">

                    <?= $this->tag->linkTo('signup', 'Daftar Akun!'); ?>

                </div>

                </form>
            </div>
        </div>
</div>
<script src="<?php echo $this->url->get('jst/login.js') ?>"></script>
